hostname: bigbang.dev
        
kubePrometheusStack:
  enabled: true
  nameOverride: monitoring

  kube-state-metrics:
    imagePullSecrets:
    - name: private-registry
    image:
      repository: registry1.dsop.io/ironbank/opensource/coreos/kube-state-metrics
      tag: v1.9.7

  alertmanager:
    enabled: true
    alertmanagerSpec:
      image:
        repository: registry1.dsop.io/ironbank/opensource/prometheus/alertmanager
        tag: v0.21.0

  grafana:
    enabled: true
    image:
      repository: registry1.dsop.io/ironbank/opensource/grafana/grafana
      tag: 7.1.3-1
      pullSecrets:
      - private-registry
    sidecar:
      image:
        # needs to be ironbanked
        repository: kiwigrid/k8s-sidecar
        tag: 1.1.0

  prometheus:
    enabled: true
    prometheusSpec:
      portName: http-web
      image:
        repository: registry1.dsop.io/ironbank/opensource/prometheus/prometheus
        tag: v2.22.0 

  prometheus-node-exporter:
    image:
      repository: registry1.dsop.io/ironbank/opensource/prometheus/node-exporter 
      tag: v1.0.1
    serviceAccount:
      imagePullSecrets:
      - name: private-registry


  prometheusOperator:
    enabled: true
    image:
      repository: registry1.dsop.io/ironbank/opensource/coreos/prometheus-operator
      tag: v0.42.1
    prometheusConfigReloaderImage:
      repository: registry1.dsop.io/ironbank/opensource/coreos/prometheus-config-reloader
      tag: v0.42.1
    configmapReloadImage:
      repository: registry1.dsop.io/ironbank/opensource/jimmidyson/configmap-reload
      tag: v0.4.0
    createCustomResource: true
    manageCrds: true
  

istio:
  enabled: true
