istio:
  enabled: true
  gateway: istio-ingressgateway.istio-system.svc.cluster.local

prometheusoperator:
  enabled: true

  # Override name so that $fullName can be used across charts
  nameOverride: "monitoring"

  prometheusOperator:
    tlsProxy:
      enabled: false
#    admissionWebhooks:
#      enabled: false

  alertmanager:
    service:
      port: 9093

  grafana:
    service:
      port: 80

  prometheus:
    service:
      port: 9090
