{{- if and .Values.networkPolicies.enabled .Values.networkPolicies.alertmanager.enableEgress }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-alertmanager-outbound-tls
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  policyTypes:
  - Egress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          # ONLY Block requests to cloud metadata IP
          except:
            - 169.254.169.254/32
{{- end }}
