{{- if and .Values.networkPolicies.enabled .Values.snmpExporter.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-snmp-exporter-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ default "prometheus-snmp-exporter" .Values.snmpExporter.nameOverride }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: prometheus
    ports:
    - port: {{ .Values.snmpExporter.service.port }}
      protocol: TCP
{{- end }}