repos:
- repo: https://repo1.dsop.io/platform-one/plugins/pre-commit-bootstraps.git
  rev: v0.2.0
  hooks:
  # Monitoring
  - id: kustomize
    name: validate kustomize - core dashboards
    args:
      - deploy/dashboards/core
  - id: kustomize
    name: validate kustomize - core service-monitors
    args:
      - deploy/service-monitors/core
  - id: helm
    name: validate helm - monitoring prometheus-operator
    alias: prometheus-operator
    args:
      - chart/