repos:
- repo: https://repo1.dsop.io/platform-one/plugins/pre-commit-bootstraps.git
  rev: v0.2.0
  hooks:
  # Monitoring
  - id: kustomize
    name: validate kustomize - monitoring dashboards
    args:
      - apps/dashboards/argocd
  - id: kustomize
    name: validate kustomize - monitoring service-monitors
    args:
      - apps/service-monitors/argocd
  - id: helm
    name: validate helm - monitoring prometheus-operator
    alias: prometheus-operator
    args:
      - chart/