{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.alloy.enabled }}
# Allows alloy to push metrics to Prometheus API
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: alloy-prometheus-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.alloy.namespaces }}
        principals: {{ .Values.istio.hardened.alloy.principals }}
    to:
    - operation:
        methods:
        - POST
        paths:
        - /api/v1/write
  selector:
    matchLabels:
      app: prometheus
{{- end }}