{{- if and .Values.istio.enabled (or .Values.istio.hardened.enabled .Values.sso.enabled) -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: shared-monitoring-authz-policy
  namespace: {{ .Values.istio.namespace }}
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ .Release.Namespace }}
        principals:
        - cluster.local/ns/{{ .Release.Namespace }}/sa/{{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
  {{- if and (not .Values.istio.clusterWideHardenedEnabled) .Values.sso.enabled }}
  selector:
    matchLabels:
      {{ .Values.sso.selector.key | default "protect" }}: {{ .Values.sso.selector.value | default "keycloak" | quote }}
  {{- end }}
{{- end }}
