{{- if .Values.istio.enabled -}}
{{- $fullName := include "grafana.fullname" . }}
{{- $serviceName := printf "%s-%s" $fullName "grafana" }}
{{- $servicePort := .Values.prometheusoperator.grafana.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $serviceName }}
  namespace: {{ template "grafana.namespace" . }}
spec:
  hosts:
    {{- if .Values.prometheusoperator.grafana.ingress.hosts }}
    {{- range .Values.prometheusoperator.grafana.ingress.hosts }}
    - {{ . }}
    {{- end }}
    {{- end }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - route:
        - destination:
            host: {{ .Release.Name }}-grafana
            port:
              number: {{ .Values.prometheusoperator.grafana.service.port }}
  {{- end }}