{{- if .Values.istio.enabled -}}
{{- $fullName := include "prometheus-operator.fullname" . }}
{{- $serviceName := printf "%s-%s" $fullName "prometheus" }}
{{- $servicePort := .Values.prometheusoperator.prometheus.service.port -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    {{- if .Values.prometheusoperator.prometheus.ingress.hosts }}
    {{- range .Values.prometheusoperator.prometheus.ingress.hosts }}
    - {{ . }}
    {{- end }}
    {{- end }}
  gateways:
    - {{ .Values.istio.gateway }}
  http:
    - route:
        - destination:
            host: {{ $serviceName }}
            port:
              number: {{ .Values.prometheusoperator.prometheus.service.port }}
  {{- end }}
