{{- if and .Values.istio.enabled .Values.istio.grafana.enabled -}}
{{- $serviceName := printf "%s-%s" .Release.Name "grafana" }}
{{- $servicePort := .Values.grafana.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-grafana
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-grafana
  {{- include "kube-prometheus-stack.labels" . | indent 4 }}
  {{- if .Values.istio.grafana.labels }}
{{ toYaml .Values.istio.grafana.labels | indent 4 }}
  {{- end }}
  {{- if .Values.istio.grafana.annotations }}
  annotations:
{{ toYaml .Values.istio.grafana.annotations | indent 4 }}
  {{- end }}
spec:
  gateways:
  {{- range .Values.istio.grafana.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.grafana.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
    - route:
        - destination:
            port:
              number: {{ .Values.istio.grafana.port  | default $servicePort }}
            host: {{ .Values.istio.grafana.service  | default $serviceName }}.{{ .Values.istio.grafana.namespace | default .Release.Namespace }}.svc.cluster.local
{{- end }}
