{{- if and .Values.prometheus.enabled .Values.istio.enabled -}}
{{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" }}
{{- $servicePort := .Values.prometheus.service.port -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-prometheus
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
spec:
  gateways:
    - main.istio-system.svc.cluster.local
  hosts:
    - "prometheus.{{ .Values.hostname }}"
  http:
    - route:
        - destination:
            port:
              number: {{ $servicePort }}
            host: {{ $serviceName }}
{{- end }}