{
 "title": "Anchore General",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "description": "Memory usage (virtual and resident) per container",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes",
     "legendFormat": "Resident Memory Bytes {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes",
     "legendFormat": "Virtual Memory Bytes {{instance}}"
    }
   ]
  },
  {
   "title": "Feed Driver Processed Record Rates",
   "type": "graph",
   "description": "The number of records processed by a driver over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(anchore_feeds_record_processing_time_count[1m]) ",
     "legendFormat": "{{driver}}"
    }
   ]
  },
  {
   "title": "Policy Evaluation Latencies Histogram",
   "type": "graph",
   "description": "Policy evaluation performance",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(anchore_policy_evaluation_time_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Request Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Queue Lengths",
   "type": "graph",
   "description": "Size of various internal queues over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "anchore_queue_length", "legendFormat": "{{queuename}}" }
   ]
  },
  {
   "title": "Image Analysis Durations",
   "type": "graph",
   "description": "Time taken to analyze images on the worker. Includes everything except queue wait time.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(anchore_analysis_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "Analyses count"
    }
   ]
  }
 ]
}