apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gatekeeper-audit
spec:
  selector:
    matchLabels:
      gatekeeper.sh/system: "yes"
      control-plane: audit-controller
  endpoints:
    - interval: 30s
      port: metrics
