{{- if and .Values.istio.enabled (eq .Values.istio.injection "enabled") }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: monitoring
  namespace: monitoring
spec:
  mtls:
    mode: {{ .Values.istio.mtls.mode }}
{{- end }}
