{{- if and .Values.istio.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
{{- if or .Values.istio.prometheusRule.IstioSidecarMemModerate .Values.istio.prometheusRule.IstioSidecarMemHigh .Values.istio.prometheusRule.IstioConfigValidationFailed .Values.istio.prometheusRule.Istio5XXResponseCode .Values.istio.prometheusRule.IstioSidecarEndpointError .Values.istio.prometheusRule.IstioSidecarListenerConflict }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: istio-prometheus-rules
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: istio.rules
    rules:
    {{- if and .Values.istio.prometheusRule.IstioSidecarMemModerate }}
    - alert: IstioSidecarMemModerate
      annotations:
        description: Istio Sidecar Memory is above 50MB for {{`{{`}} $labels.pod_name {{`}}`}}
        summary: Istio Sidecar Memory usage is above average
        # "0.00000095357432" multiplier used to convert Bytes to Megabytes to make human readable
      expr: istio_agent_go_memstats_heap_sys_bytes{} * 0.00000095357432 > 50
      for: 1h
      labels:
        severity: warning
    {{- end }}
    {{- if and .Values.istio.prometheusRule.IstioSidecarMemHigh }}
    - alert: IstioSidecarMemHigh
      annotations:
        description: Istio Sidecar Memory is above 100MB for {{`{{`}} $labels.pod_name {{`}}`}}
        summary: Istio Sidecar Memory usage is very high
        # "0.00000095357432" multiplier used to convert Bytes to Megabytes to make human readable
      expr: istio_agent_go_memstats_heap_sys_bytes{} * 0.00000095357432 > 100
      for: 1h
      labels:
        severity: critical
    {{- end }}
    {{- if and .Values.istio.prometheusRule.IstioConfigValidationFailed }}
    - alert: IstioConfigValidationFailed
      annotations:
        description: Istio Configuration Validation Error
        summary: Istio's Galley Reports a Configuration Validation Error
      expr: sum(rate(galley_validation_failed[5m])) > 0
      for: 2m
      labels:
        severity: critical
    {{- end }}
    {{- if and .Values.istio.prometheusRule.Istio5XXResponseCode }}
    - alert: Istio5XXResponseCode
      annotations:
        description: Multiple {{`{{`}} $labels.reponse_code {{`}}`}} Errors for pod {{`{{`}} $labels.pod_name {{`}}`}}
        summary: Istio Mesh is Reporting 5XX Errors from Applications in-mesh
      expr: istio_requests_total{reporter="source",response_code=~"5.*"} >= 1
      for: 10m
      labels:
        severity: critical
    {{- end }}
    {{- if and .Values.istio.prometheusRule.IstioSidecarEndpointError }}
    - alert: IstioSidecarEndpointError
      annotations:
        description: Istio Sidecar Agent Not Ready for pod {{`{{`}} $labels.pod_name {{`}}`}} in namespace {{`{{`}} $labels.namespace {{`}}`}}
        summary: One or more Istio Sidecars are Not Ready
      expr: istio_agent_pilot_endpoint_not_ready{} >= 1
      for: 10m
      labels:
        severity: critical
    {{- end }}
    {{- if and .Values.istio.prometheusRule.IstioSidecarListenerConflict }}
    - alert: IstioSidecarListenerConflict
      annotations:
        description: Istio Sidecar Agent Has Listener Conflict for pod {{`{{`}} $labels.pod_name {{`}}`}} in namespace {{`{{`}} $labels.namespace {{`}}`}}
        summary: One or more Istio Sidecars have a Listener Conflict
      expr: istio_agent_pilot_conflict_inbound_listener{} >= 1
      for: 10m
      labels:
        severity: warning
    {{- end }}
{{- end }}
{{- end }}
